### ISSUE TITLE
Cannot start the server on windows.

### ISSUE THREAD

**Issue by prabhath6** [jacekschae/learn-reagent-course-files#1]
I was going through the second lesson `02 App Setup` in the series and tried to start the server by running `npm run dev` after installing all the npm packages, it failed to start.
```
> npm run dev

> Giggin@0.0.1 dev C:\Users\xyz\Desktop\projects\learn-reagent-course-files-master\giggin
> shadow-cljs watch app;

shadow-cljs - config: C:\Users\xyz\Desktop\projects\learn-reagent-course-files-master\giggin\shadow-cljs.edn  cli version: 2.4.12  node: v10.5.0
shadow-cljs - starting ...
No config for build "app;" found.
Build id required.
```

I followed the same instructions on Ubuntu and it worked as expected. Are there different projects setups for windows and other Unix environments. Is there a way to fix this on windows.

**Comment by jacekschae** [comment]
Sorry to hear about your problem on Windows.
There is no difference in setup for Windows -- it's just npm package.

@thheller is there anything you could advise here?

**Comment by thheller** [comment]
`No config for build "app;" found.`

The `;` seems to be passed along on windows, probably just need to remove it from the npm script?

**Comment by jacekschae** [comment]
@prabhath6 could you try this out? If that works I'll correct the script files. 

Thanks @thheller!

**Comment by prabhath6** [comment]
thanks, @jacekschae, and @thheller it fixed it.
```
  "scripts": {
    "dev": "shadow-cljs watch app",
    "release": "shadow-cljs release app",
    "clean": "rm -rf target; rm -rf public/js;"
}
```

I changed the `dev` and `release` commands. I could not figure out the equivalent command to remove target and js folders. The other thing that worked is using WSL to start the server and access it from the browser.

**Comment by Biserkov** [comment]
@prabhath6  The equivalent command to remove target and js folder would be:

`rmdir /s /q public\js & rmdir /s /q target`

**Comment by prabhath6** [comment]
@Biserkov Thanks I will try that out.

**Comment by jacekschae** [comment]
thx @Biserkov 

Just wondering about this one. Should we add another clean for windows?
```
clean-win: "rmdir /s /q public\js & rmdir /s /q target"
```

I'm not big on win dev and thought that if someone uses win they would also be using some kind of bash emulator. Any thoughts @Biserkov @prabhath6?

**Comment by Biserkov** [comment]
@jacekschae Well, having a clean that works on Windows is a clean win :-) 

Since it requires no effort and doesn't cause any compatibility problems, I don't see why not.

It's much more convenient to get Node and Java via the installers.

**Comment by thheller** [comment]
FWIW I think some node packages are using the [rimraf](https://www.npmjs.com/package/rimraf) package which I think is cross platform and can be used just like `rm -rf`

**Comment by jacekschae** [comment]
I added the clean win,

thanks @prabhath6 @Biserkov and @thheller
