### ISSUE TITLE
`gigs` returns a function in `14 Gig Editor` but it was never added

### ISSUE THREAD

**Issue by filipesilva** [jacekschae/learn-reagent-course-files#10]
`13 Checkout Modal` does mention at the end that components that hold state should return a function and changes `checkout-modal.cljs` to do so. But `gigs` does not return a function last time it shows up at the end of `12 Refactor Functions`, and then it does at the start of `14 Gig Editor` without the video saying it should change.

This causes a subtle bug later. Near the end of `15 Save Gig` we add `(reset! modal false)` to the `insert-gig` function so that clicking save also closes the modal. But this doesn't change any behaviour if you haven't added the function return to `gigs` (like I didn't) since the previous swap triggers a rerender and resets modal anyway.

**Comment by jacekschae** [comment]
Hi there, I'm sorry for the late reply on this one - somehow even thought I watch the repo - I don't get any notifications. Thanks so much for your feedback and noticing this problem with `gigs` I'll take a look and see how I can fix it between 12 and 14.

**Comment by jacekschae** [comment]
Added a comment as you provided in the description and included the attribution. Thanks!
