### ISSUE TITLE
The tag <tag> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

### ISSUE THREAD

**Issue by ghost** [jacekschae/learn-reagent-course-files#14]
Hello Jacek,

I'm stuck on video 04 First Components because of the following warnings:

warning.js:34 Warning: The tag `<gigs>` is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

warning.js:34 Warning: The tag `<orders>` is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

Since those components are not rendered properly, the style.css isn't applied to those components.

Do you have any pointers on how to fix this?

Thanks.

**Comment by jacekschae** [comment]
Thanks for reaching out - yeah I do have pointers - did you take a look at increments and solutions - https://github.com/jacekschae/learn-reagent-course-files/tree/master/increments/05-displaying-gigs/src/giggin ?

If this doesn't help let me know, Jacek

**Comment by ghost** [comment]
Yeah I did, I copied the src folder from lesson 05 and it still gives me the same warning but the css is working at least.

I then copied the src folder from lesson 17 and the warning is gone, even though the component has the same name.

I'll close the issue since it's not blocking me from further progressing in the course.

Thanks for the help.

**Comment by jacekschae** [comment]
There will be some more things like that - it's sometimes hard to fix everything in one video. Keep with the course and when there are issues they will be fixed in following videos. Thanks for reaching out!
