### ISSUE TITLE
"for" over orders in orders.cljs

### ISSUE THREAD

**Issue by okc0mputer** [jacekschae/learn-reagent-course-files#18]
the code 
`(for [[id quant] @state/orders]`
leaves me wondering because I was under the impression Clojure maps are not guaranteed to be returned in any specific order, so how can you use a list comprehension on a map with certainty that you will get the correct values?

**Comment by jacekschae** [comment]
That is correct maps do not guarantee order. It doesn't mean the values will be incorrect - key will always correspond to value. If you would like to guarantee order you could, instead of using `{:key val}`, use `(sorted-map :key value)`.

**Comment by okc0mputer** [comment]
Thank you for the reply, I have a better understanding now.  I was thinking it would be better to use the keys in order to make sure the data was correct, but I guess for such a simple map it won't be possible to bind the wrong data to a var, correct?

**Comment by jacekschae** [comment]
The order guarantee is not for the `key-value` -- this will be always correctly bound. The order is not guaranteed for which `key-value` will be displayed first, second, or next.

If you define a map 

```clojure
{:one 1
 :two 2
 :three 3}
```

and then you decide to `map` over:

```clojure
(map identity {:one 1
               :two 2
               :three 3})
```

You might not get them in correct order

```clojure
=> ([:one 1] [:two 2] [:three 3])

=> ([:one 1] [:three 3] [:two 2])
```

> Note: this is a contrived example for bigger maps this would be more realistic than for smaller ones. 

One more time: the order guarantee is not for binding `key` to `value` but for which `key-value` pair will be displayed first second, or next ... .

Hope that helps.

**Comment by okc0mputer** [comment]
This will be my last post,  I promise.  I understand the keys and values will always be correctly bound to each other.   What I'm not understanding is when we do, for example using a simple map `(for [[id quant] {:gig01 1}]...)` , how exactly those vars get bound.  It would seem the map is turned into a seq of pairs and each pair gets the its key bound to `id` and the value to `quant` during the comprehension ?

**Comment by jacekschae** [comment]
Don't worry about asking questions.

That is exactly right; how you described it. 

From the description you can deduct that maps `{}` are similar to vectors `[]`. In vector the key is index from 0 ... n, and in a map the index is a `key` whatever you decide to name it. 

```clojure

;; Vector
(map-indexed (fn [k v] [k v]) [:one :two :three :four :five])

=> ([0 :one] [1 :two] [2 :three] [3 :four] [4 :five])
```

docs: [map-indexed](https://clojuredocs.org/clojure.core/map-indexed)



Hope this conversation helps in understanding how things works, and from what I see you understand how this works.

**Comment by okc0mputer** [comment]
Thanks for your patience while I figured all this out.  The gigs comprehension was much easier to understand because of the destructuring used, but in this case I was left wondering how the vars were being bound to the correct values without needing to destructure them.  It was your usage of the `identity` function that helped me to come to an understanding of the mechanics behind this code.  Really great course for a Clojure newbie like myself, and I will certainly continue with the full version afterwards
