### ISSUE TITLE
Calva and Shadow cljs

### ISSUE THREAD

**Issue by GerriDad** [jacekschae/learn-reagent-course-files#22]
<img width="1141" alt="Screenshot 2022-11-23 at 4 04 03 PM" src="https://user-images.githubusercontent.com/117367590/203688088-7bb5ec6c-5843-4936-bc4d-0f3c90986b62.png">

I'm not sure what issue is here. Is it a npm run vs jack-in issue?  I'm using VS Code and Calva and things were fine checking the blank page on localhost:3000 to begin with, then when I completed the components section (#4) and tried it I got the message at the bottom of the screen. I also may be misunderstanding the purpose of Jacking-In and the REPL. 

It seems like there may be a REPL running that I'm unaware of, or how to kill. 

Any help is much appreciated.

**Comment by jacekschae** [comment]
I would recommend to open localhost:9630 (shadow-cljs ui) and see what is going on there. It might give more insides into how to debug this.

**Comment by jacekschae** [comment]
Also from @thheller:

if you upgrade the files to the latest versio there is a warning about this
most probably this is running 2 instances locally
one via jack-in and one via npx shadow-cljs watch
common problem for emacs people and vscode as well I guess
either use npm run or jack-in  -- not both

**Comment by GerriDad** [comment]
Yep, it was npx issues. Great insight on the lh:9630, as well. Thank you for you time, Jacek, it's much appreciated.
