### ISSUE TITLE
Bug: Learn Reagent Pro: upsert-gig on the gigs.cljs

### ISSUE THREAD

**Issue by evedes** [jacekschae/learn-reagent-course-files#24]
Hey @jacekschae , I've noticed a small bug in the 16th video (Update Gig) at minute 4:56 where we refactor insert-gig to upsert-gig.

The way to replicate the bug is to create a gig, and then, after saving it, update it.

So the problem has to do with the id of the map, which goes empty when we create a new gig.

![CleanShot 2023-02-20 at 21 06 24](https://user-images.githubusercontent.com/956832/220199688-3421c400-6c81-4d2f-a188-c12484ff720f.png)

For me one solution could be: 

![CleanShot 2023-02-20 at 21 17 58](https://user-images.githubusercontent.com/956832/220199883-59f0171b-6343-469c-bf57-7147683ef408.png)

But I don't know if you have a better solution.

I could open a PR but I'm still doing the course, so I don't know if you fix it sometime after. Besides that, this needs to be fixed in all the branches from 17 up.

**Comment by jacekschae** [comment]
Thanks fro this. It's fixed in the next video.
