### ISSUE TITLE
Reagent 21 Firebase Database: regenerator-runtime/runtime required in order to use the realtime database.

### ISSUE THREAD

**Issue by kentbull** [jacekschae/learn-reagent-course-files#26]
I found that I had to `npm i -s regenerator-runtime` and `(:require ["regenerator-runtime/runtime"]` prior to the `["firebase/database" :as fb]` dependency in order to get rid of the following error:

"Uncaught ReferenceError: regeneratorRuntime is not defined"

It looks like the Firebase Realtime database library uses the [Regenerator](https://www.npmjs.com/package/regenerator-runtime) library to generate some of their functions and thus is required when using the latest version of Firebase (9.23.0).

**Comment by jacekschae** [comment]
Thanks for the feedback Kent! Just added to the video and included the credit!

<img width="614" alt="Screenshot 2023-07-02 at 09 38 32" src="https://github.com/jacekschae/learn-reagent-course-files/assets/31179812/6969915c-1181-4f70-b79b-22b938d439af">
