### ISSUE TITLE
nrepl Error Spacemacs

### ISSUE THREAD

**Issue by dilzeem** [jacekschae/learn-reagent-course-files#6]
Current doing the course, but it seems like I get some weird error while on Episode 7.

`No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.`

It seems you may have had a similar issue as well: https://github.com/thheller/shadow-cljs/issues/269. Did you ever find out what the cause of this was?

When I write:
`(shadow.cljs.devtools.api/nrepl-select :app)` it actually works and I get `[:selected :app]`. 

But when I input:
````
(ns giggin.state
             (:require [reagent.core :as r]))' 
````
I get the error `No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.`

**Comment by jacekschae** [comment]
Make sure that your server finished compiling and that after that you connect with yoru browser (this is accomplished by simply opening the brwoser on the server, normally localhost:3000). 

I think this was the cause. I had a couple of servers and somehow the build got confused which one it should connect to.

Also try to load files with `Proto Repl: Load Current File`
<img width="578" alt="screen shot 2019-02-26 at 01 12 48" src="https://user-images.githubusercontent.com/31179812/53377829-b1db5e00-3963-11e9-9391-0aa469d9f683.png">

Hope that helps, please let me know if I can help any further!

**Comment by dilzeem** [comment]
Okay I got it working, 

It involved some extra commands specific to CIDER/Emacs, located here.
https://shadow-cljs.github.io/docs/UsersGuide.html#cider

Also had to ensure that browser had page displayed as discussed here:
https://clojureverse.org/t/shadow-cljs-and-leinigen-and-npm-oh-my/2735/16

Thank you for your response.
