### ISSUE TITLE
Unable to build a production build for a derivative project 

### ISSUE THREAD

**Issue by abhi18av** [jacekschae/learn-reagent-course-files#7]
Hi @jacekschae, 

I've been learning a lot from your videos and to take the next step I decided to build a simple snake game for myself here https://github.com/abhi18av/luminus-snake/tree/b2.0.0 

The thing is as of now, only the `npm run dev` works fine and not the `npm run release`. The latter throws the error `ReferenceError: snake is not defined` in the console. Could you guide me a bit here please?

**Comment by abhi18av** [comment]
Whoops, I've debugged this one. The solution was simply to add the proper relative file name in the `index.html`. But then arises a different problem with the `release compiled javascript` and it throws the following error in the browser.

```
TypeError: snake.core.init is not a function
```

Perhaps, this is another quick fix but nothing strikes my mind as of now.

**Comment by jacekschae** [comment]
Seems like you are exporting `main` and not `init`

```
defn init []
  ;; init is called ONCE when the page loads
  ;; this is called in the index.html and must be exported
  ;; so it is available even in :advanced release builds
 ;(js/console.log "init")



 ;; Resize canvas object
 (resize-canvas)
  ;; Remove all listen events
 (events/removeAll js/document)
  ;; Register event listener `on-keydown` event
 (events/listen js/document goog.events.EventType.KEYDOWN on-keydown)
  ;; Start the game loop
(game-loop))

(defn ^:export main
  []
  (r/render
    [app]
    (.getElementById js/document "app")))
```

When you don't add `^:export` before `init`, or any function name that you want to access from html file it will be shortened by the google closure compiler and might end up as - let's say `c` - in this way it cannot find the `init` function. Therefore the error.

You can also change the way you setup shadow-cljs and don't worry about the `^:export` - check out [learn re-frame setup](https://github.com/jacekschae/learn-re-frame-course-files/blob/44d908d531b184ca82fe0bd60e663312e66d1168/increments/complete/shadow-cljs.edn#L22) In this way you have `init-fn` which takes care of `^:export` and the only thing you need to add to [index.html](https://github.com/jacekschae/learn-re-frame-course-files/blob/44d908d531b184ca82fe0bd60e663312e66d1168/increments/complete/public/index.html#L17) is the a script name.

Hope that helps, if you would have any further questions let me know.

**Comment by abhi18av** [comment]
Ahh, yes - that's true! I'll be for sure covering up the re-frame tutorial today itself. Thanks @jacekschae , your course has been one of the best learning experiences for people learning `ClojureScript` 👍
