### ISSUE TITLE
use a more recent shadow-cljs version

### ISSUE THREAD

**Issue by little-dude** [jacekschae/learn-reagent-course-files#8]
Currently the project uses 2.3.30, which pulls in an old version of nrepl, causing integration issues with cider: https://github.com/clojure-emacs/cider/issues/2652

Updating to 2.8.39 solves the issue with cider.

**Comment by jacekschae** [comment]
Thanks for the issue and I'm sorry for my late reply - I don't know why I didn't get notified about this one even thought I'm wathing the repo - just upaded to the latest shadow-cljs
